# -*- coding: utf-8 -*-
"""02. Projeto .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aoTsN5ZaN18ZV1LexTRjNItMhXa4ndmL

# Análise de Dados com Python

Passo a passo:

1. Importar os dados;
2. Visualizar os dados;
3. Data Cleaning;
4. Análise simples;
5. Análise complexa.
"""

# Importando as bibliotécas.
import pandas as pd
import plotly.express as px
# Documentação: https://plotly.com/python/histograms/

# 1. Importando os dados.
df = pd.read_csv("/content/DataSet_telecom_users.csv")

# 2. Visualizando os dados.
df.head() # Para entender do que se trata!

# Eliminando a coluna "Unnamed: 0", já que ela não agrega na análise, nesse momento.
# Algo importante, é nunca eliminar dados da Df sem saber de onde eles vem.
# Mas para esse exercício, iremos excluir essa coluna em específico.
df = df.drop("Unnamed: 0", axis=1)
display(df)

# 3. Data Cleaning.
print(df.info())

# Cast a coluna TotalGasto de Str para Int;
df["TotalGasto"] = pd.to_numeric(df["TotalGasto"], errors="coerce")
# Linhas com valores vazios "Dependentes" e "Churn";
# Excluir colunas vazias;
df = df.dropna(how="all", axis=1)
# Excluir linhas vazias;
df = df.dropna(how="any", axis=0)
print(df.info())

# 4. Análise simples;
print(df["Churn"].value_counts())
print(df["Churn"].value_counts(normalize=True).map("{:.1%}".format))

# 5. Análise complexa.
# etapa 1: criar o gráfico
for coluna in df.columns:
    # para edições nos gráficos: https://plotly.com/python/histograms/
    # para mudar a cor do gráfico , color_discrete_sequence=["blue", "green"]
    grafico = px.histogram(df, x=coluna, color="Churn")
    # etapa 2: exibir o gráfico
    grafico.show()

"""### Conclusões e Ações

Escreva aqui suas conclusões:
"""